"""empty message

Revision ID: 21223fb0e029
Revises: 
Create Date: 2018-06-17 16:28:54.533696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21223fb0e029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announce', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('faculty_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('roleid')
    )
    op.create_table('undergrad',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.Text(), nullable=False),
    sa.Column('fname', sa.String(length=15), nullable=False),
    sa.Column('lname', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=15), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('faculty', sa.Integer(), nullable=False),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['faculty'], ['faculty.faculty_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('cv', sa.Boolean(), nullable=True),
    sa.Column('cgpa', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Boolean(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['undergrad.u_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.roleid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('project')
    op.drop_table('users')
    op.drop_table('department')
    op.drop_table('undergrad')
    op.drop_table('roles')
    op.drop_table('faculty')
    op.drop_table('announcement')
    # ### end Alembic commands ###
